@props(['label'])

<label for="{{ $attributes['id'] }}" class="block text-base font-semibold leading-6">
    {{ $label }}
</label>
<div class="mt-2">
    <select {{ $attributes }}
            class="block p-4 px-6 w-full rounded-md border-0 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 font-medium focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:leading-6">
        <option value=""></option>
        <option value="af">Afrikaans</option>
        <option value="ak">Akan</option>
        <option value="sq">Albanian</option>
        <option value="am">Amharic</option>
        <option value="ar">Arabic</option>
        <option value="hy">Armenian</option>
        <option value="as">Assamese</option>
        <option value="az">Azerbaijani</option>
        <option value="bm">Bambara</option>
        <option value="eu">Basque</option>
        <option value="be">Belarusian</option>
        <option value="bn">Bengali</option>
        <option value="bs">Bosnian</option>
        <option value="br">Breton</option>
        <option value="bg">Bulgarian</option>
        <option value="my">Burmese</option>
        <option value="ca">Catalan</option>
        <option value="zh">Chinese</option>
        <option value="kw">Cornish</option>
        <option value="hr">Croatian</option>
        <option value="cs">Czech</option>
        <option value="da">Danish</option>
        <option value="nl">Dutch</option>
        <option value="dz">Dzongkha</option>
        <option value="en">English</option>
        <option value="et">Estonian</option>
        <option value="ee">Ewe</option>
        <option value="fo">Faroese</option>
        <option value="fi">Finnish</option>
        <option value="fr">French</option>
        <option value="ff">Fulah</option>
        <option value="gl">Galician</option>
        <option value="lg">Ganda</option>
        <option value="ka">Georgian</option>
        <option value="de">German</option>
        <option value="el">Greek</option>
        <option value="gu">Gujarati</option>
        <option value="ha">Hausa</option>
        <option value="he">Hebrew</option>
        <option value="hi">Hindi</option>
        <option value="hu">Hungarian</option>
        <option value="is">Icelandic</option>
        <option value="ig">Igbo</option>
        <option value="id">Indonesian</option>
        <option value="ga">Irish</option>
        <option value="it">Italian</option>
        <option value="ja">Japanese</option>
        <option value="kl">Kalaallisut</option>
        <option value="kn">Kannada</option>
        <option value="ks">Kashmiri</option>
        <option value="kk">Kazakh</option>
        <option value="km">Khmer</option>
        <option value="ki">Kikuyu</option>
        <option value="rw">Kinyarwanda</option>
        <option value="ko">Korean</option>
        <option value="ky">Kyrgyz</option>
        <option value="lo">Lao</option>
        <option value="lv">Latvian</option>
        <option value="ln">Lingala</option>
        <option value="lt">Lithuanian</option>
        <option value="lu">Luba-Katanga</option>
        <option value="lb">Luxembourgish</option>
        <option value="mk">Macedonian</option>
        <option value="mg">Malagasy</option>
        <option value="ms">Malay</option>
        <option value="ml">Malayalam</option>
        <option value="mt">Maltese</option>
        <option value="gv">Manx</option>
        <option value="mr">Marathi</option>
        <option value="mn">Mongolian</option>
        <option value="ne">Nepali</option>
        <option value="nd">North Ndebele</option>
        <option value="se">Northern Sami</option>
        <option value="no">Norwegian</option>
        <option value="nb">Norwegian Bokm&aring;l</option>
        <option value="nn">Norwegian Nynorsk</option>
        <option value="or">Oriya</option>
        <option value="om">Oromo</option>
        <option value="os">Ossetic</option>
        <option value="ps">Pashto</option>
        <option value="fa">Persian</option>
        <option value="pl">Polish</option>
        <option value="pt">Portuguese</option>
        <option value="pa">Punjabi</option>
        <option value="qu">Quechua</option>
        <option value="ro">Romanian</option>
        <option value="rm">Romansh</option>
        <option value="rn">Rundi</option>
        <option value="ru">Russian</option>
        <option value="sg">Sango</option>
        <option value="gd">Scottish Gaelic</option>
        <option value="sr">Serbian</option>
        <option value="sh">Serbo-Croatian</option>
        <option value="sn">Shona</option>
        <option value="ii">Sichuan Yi</option>
        <option value="si">Sinhala</option>
        <option value="sk">Slovak</option>
        <option value="sl">Slovenian</option>
        <option value="so">Somali</option>
        <option value="es">Spanish</option>
        <option value="sw">Swahili</option>
        <option value="sv">Swedish</option>
        <option value="tl">Tagalog</option>
        <option value="ta">Tamil</option>
        <option value="te">Telugu</option>
        <option value="th">Thai</option>
        <option value="bo">Tibetan</option>
        <option value="ti">Tigrinya</option>
        <option value="to">Tongan</option>
        <option value="tr">Turkish</option>
        <option value="uk">Ukrainian</option>
        <option value="ur">Urdu</option>
        <option value="ug">Uyghur</option>
        <option value="uz">Uzbek</option>
        <option value="vi">Vietnamese</option>
        <option value="cy">Welsh</option>
        <option value="fy">Western Frisian</option>
        <option value="yi">Yiddish</option>
        <option value="yo">Yoruba</option>
        <option value="zu">Zulu</option>
    </select>
</div>
